const navIds = {
  clusterManagement: {
    dashboard: 'cluster-management-dashboard',
    events: 'cluster-management-events',
    namespaces: 'cluster-management-namespaces',
    nodes: 'cluster-management-nodes',
    persistentVolume: 'cluster-management-persistent-volume',
    storageClasses: 'cluster-management-storage-classes'
  },
  logs: {
    searching: 'logs-searching',
    settings: 'logs-settings'
  },
  projectManagement: {
    addCertificate: 'project-management-add-certificate',
    addConfigMap: 'project-management-add-config-map',
    addCredential: 'project-management-registry-add-credential',
    addHpa: 'project-management-add-hpa',
    addSecretForm: 'project-management-add-secret-form',
    addServiceDiscovery: 'project-management-add-service-discovery',
    certificate: 'project-management-certificate',
    configmap: 'project-management-configmap',
    deployment: 'project-management-deployment',
    deploymentEdit: 'project-management-deployment-edit',
    deploymentAdd: 'project-management-deployment-add',
    deploymentDetail: 'project-management-deployment-detail',
    stateful: 'project-management-stateful',
    statefulAdd: 'project-management-stateful-add',
    statefulEdit: 'project-management-stateful-edit',
    statefulDetail: 'project-management-stateful-detail',
    daemon: 'project-management-daemon',
    daemonAdd: 'project-management-daemon-add',
    daemonEdit: 'project-management-daemon-edit',
    daemonDetail: 'project-management-daemon-detail',
    detailHpa: 'project-management-detail-hpa',
    editHpa: 'project-management-edit-hpa',
    editServiceDiscovery: 'project-management-edit-service-discovery',
    editConfigMap: 'project-management-edit-config-map',
    hpa: 'project-management-hpa',
    ingress: 'project-management-ingress',
    ingressAdd: 'project-management-ingress-add',
    ingressDetail: 'project-management-ingress-detail',
    ingressEdit: 'project-management-ingress-edit',
    projects: 'project-management-projects',
    registry: 'project-management-registry',
    secret: 'project-management-secret',
    serviceDiscovery: 'project-management-service-discovery',
    serviceDiscoveryClusterDetail:
      'project-management-service-discovery-cluster-detail',
    serviceDiscoveryDetail: 'project-management-service-discovery-detail',
    volume: 'project-management-volume',
    volumeAdd: 'project-management-volume-add',
    volumeDetail: 'project-management-volume-detail'
  },
  settings: {
    addNextAPIBranding: 'settings-nextAPI-add-branding',
    addNextFlowBranding: 'settings-nextFlow-add-branding',
    addNextIDBranding: 'settings-nextID-add-branding',
    addNextWebBranding: 'settings-nextWeb-add-branding',
    apiGateway: 'settings-nextAPI-api-gateway',
    editNextAPIBranding: 'settings-nextAPI-edit-branding',
    editNextFlowBranding: 'settings-nextFlow-edit-branding',
    editNextIDBranding: 'settings-nextID-edit-branding',
    editNextWebBranding: 'settings-nextWeb-edit-branding',
    nextAPIBranding: 'settings-nextAPI-branding',
    nextFlowBranding: 'settings-nextFlow-branding',
    nextIDBranding: 'settings-nextID-branding',
    nextWebBranding: 'settings-nextWeb-branding',
    retention: 'settings-retention',
    viewNextAPIBranding: 'settings-nextAPI-view-branding',
    viewNextIDBranding: 'settings-nextID-view-branding',
    viewNextWebBranding: 'settings-nextWeb-view-branding'
  },
  distributionTracing: {
    livemap: 'distribution-tracing-livemap',
    service: 'distribution-tracing-service',
    traces: 'distribution-tracing-traces',
    tracesDetail: 'distribution-tracing-traces-detail',
    tracesDetailTime: 'distribution-tracing-traces-detail-time'
  },
  monitoringAlerting: {
    monitoringGraph: 'monitoring-alerting-monitoring-graph',
    alertingChannels: 'monitoring-alerting-alerting-channels',
    alertingRules: 'monitoring-alerting-alerting-rules',
    alertingRulesAdd: 'monitoring-alerting-alerting-rules-add',
    alertingRulesType: 'monitoring-alerting-alerting-rules-type',
    alertingTriggers: 'monitoring-alerting-alerting-triggers'
  },
  userAndRoles: {
    clusterRoles: 'user-and-roles-cluster-roles',
    clusterRolesBindings: 'user-and-roles-cluster-roles-bindings',
    roles: 'user-and-roles-roles',
    rolesDetail: 'user-and-roles-roles-detail',
    rolesDetailEdit: 'user-and-roles-roles-detail-edit',
    rolesBindings: 'user-and-roles-roles-bindings',
    rolesBindingsDetail: 'user-and-roles-roles-bindings-detail',
    rolesBindingsDetailEdit: 'user-and-roles-roles-bindings-detail-edit',
    rolesBindingsDetailResourcesInformation:
      'user-and-roles-roles-bindings-detail-resources-information',
    rolesBindingsDetailResourcesInformationEdit:
      'user-and-roles-roles-bindings-detail-resources-information-edit',
    servicesAccounts: 'user-and-roles-service-accounts',
    editserviceAccounts: 'user-and-roles-service-accounts-edit-service-accounts',
    addServiceAccounts: 'user-and-roles-service-accounts-add-service-accounts',
    servicesAccountsDetail: 'user-and-roles-service-accounts-detail',
    users: 'user-and-roles-users'
  },
  appManagement: {
    dashboard: 'app-management-dashboard',
    applications: 'app-management-applications',
    applicationsSyncAll: 'app-management-applications-sync-all',
    applicationsSyncApp: 'app-management-applications-sync-app',
    applicationsAddApplication: 'app-management-applications-add-application',
    applicationsMap: 'app-management-applications-map',
    applicationsDetail: 'app-management-applications-detail',
    userManagement: 'app-management-user-management',
    userManagementDetail: 'app-management-user-management-detail',
    settingRepositories: 'app-management-setting-repositories',
    settingRepositoriesAddSSH: 'app-management-setting-repositories-add-ssh',
    settingRepositoriesAddHTTPS: 'app-management-setting-repositories-add-https',
    settingRepositoriesAddGithub: 'app-management-setting-repositories-add-github',
    settingCertificates: 'app-management-setting-certificates',
    settingCertificatesAddTLS: 'app-management-setting-certificates-add-tls',
    settingCertificatesAddSSH: 'app-management-setting-certificates-add-ssh',
    settingClusters: 'app-management-setting-clusters',
    detailClusters: 'app-management-setting-detail-clusters',
    settingProjects: 'app-management-setting-projects',
    settingAddProjects: 'app-management-setting-add-projects',
    settingProjectsDetail: 'app-management-setting-projects-detail',
    helpOverview: 'app-management-help-overview',
    helpUnderstandTheBasic: 'app-management-help-understand-the-basic',
    helpCoreConcept: 'app-management-help-core-concept',
    helpGettingStarted: 'app-management-help-getting-started',
    helpOperatorManual: 'app-management-help-operator-manual',
    helpUserGuide: 'app-management-help-user-guide',
    helpDeveloperGuide: 'app-management-help-developer-guide',
    helpFAQ: 'app-management-help-faq',
    helpSecurityConsideration: 'app-management-help-security-consideration',
    helpSupport: 'app-management-help-support',
    helpRoadmap: 'app-management-help-roadmap',
    helpReleases: 'app-management-help-releases',
    helpBlog: 'app-management-help-blog'
  }
};

const allRoutes = {
  clusterManagement: {
    dashboard: '/cluster-management/dashboard',
    events: '/cluster-management/events',
    namespaces: '/cluster-management/namespaces',
    nodes: '/cluster-management/nodes',
    persistentVolume: '/cluster-management/storages/persistent-volume',
    storageClasses: '/cluster-management/storages/storage-classes'
  },
  logs: {
    searching: '/logs/searching',
    searchingDetail: '/logs/searching/detail/:id',
    settings: '/logs/retentionSettings'
  },
  projectManagement: {
    addCertificate: '/project-management/certificate/add-certificate',
    addConfigMap: '/project-management/configmap/addConfigMap',
    addCredential: '/project-management/registry/add-credential',
    addHpa: '/project-management/hpa/add-hpa',
    addSecretForm: '/project-management/secret/add-secret-form',
    addServiceDiscovery:
      '/project-management/service-discovery/add-service-discovery',
    certificate: '/project-management/certificate',
    configmap: '/project-management/configmap',
    deployment: '/project-management/deployment',
    deploymentEdit: '/project-management/deployment/edit/:id',
    deploymentAdd: '/project-management/deployment/add',
    deploymentDetail: '/project-management/deployment/detail/:id',
    podDetail: '/project-management/deployment/detail/:id/pod/:id',
    containerDetail: '/project-management/deployment/detail/:id/pod/:id/container/:id',
    stateful: '/project-management/stateful',
    statefulAdd: '/project-management/stateful/add',
    statefulEdit: '/project-management/stateful/edit/:id',
    statefulDetail: '/project-management/stateful/detail/:id',
    statefulPodDetail: '/project-management/stateful/detail/:id/pod/:id',
    statefulContainerDetail: '/project-management/stateful/detail/:id/pod/:id/container/:id',
    daemon: '/project-management/daemon',
    daemonAdd: '/project-management/daemon/add',
    daemonEdit: '/project-management/daemon/edit/:id',
    daemonPodDetail: '/project-management/daemon/detail/:id/pod/:id',
    daemonContainerDetail: '/project-management/daemon/detail/:id/pod/:id/container/:id',
    daemonDetail: '/project-management/daemon/detail/:id',
    detailHpa: '/project-management/hpa/detail-hpa/:id',
    editCertificate: '/project-management/certificate/edit-certificate/:id',
    editHpa: '/project-management/hpa/edit-hpa/:id',
    editConfigMap: '/project-management/configmap/editConfigMap/:id',
    editSecretForm: '/project-management/secret/edit-secret-form/:id',
    editServiceDiscovery:
      '/project-management/service-discovery/edit-service-discovery/:id',
    hpa: '/project-management/hpa',
    ingress: '/project-management/ingress',
    ingressAdd: '/project-management/ingress/add',
    ingressDetail: '/project-management/ingress/detail/:id',
    ingressEdit: '/project-management/ingress/edit/:id',
    projects: '/project-management/projects',
    registry: '/project-management/registry',
    secret: '/project-management/secret',
    serviceDiscovery: '/project-management/service-discovery',
    serviceDiscoveryClusterDetail:
      '/project-management/service-discovery/cluster-detail/:id',
    serviceDiscoveryDetail: '/project-management/service-discovery/detail/:id',
    volume: '/project-management/volume',
    volumeAdd: '/project-management/volume/add',
    volumeDetail: '/project-management/volume/detail'
  },
  settings: {
    addNextAPIBranding: '/settings/nextAPI/branding/add',
    addNextFlowBranding: '/settings/nextFlow/branding/add',
    addNextIDBranding: '/settings/nextID/branding/add',
    addNextWebBranding: '/settings/nextWeb/branding/add',
    apiGateway: '/settings/nextAPI/api-gateway',
    editNextAPIBranding: '/settings/nextAPI/branding/edit/:id',
    editNextFlowBranding: '/settings/nextFlow/branding/edit/:id',
    editNextIDBranding: '/settings/nextID/branding/edit/:id',
    editNextWebBranding: '/settings/nextWeb/branding/edit/:id',
    nextAPIBranding: '/settings/nextAPI/branding',
    nextFlowBranding: '/settings/nextFlow/branding',
    nextIDBranding: '/settings/nextID/branding',
    nextWebBranding: '/settings/nextWeb/branding',
    retention: '/settings/retention',
    viewNextAPIBranding: '/settings/nextAPI/branding/view/:id',
    viewNextFlowBranding: '/settings/nextFlow/branding/view/:id',
    viewNextIDBranding: '/settings/nextID/branding/view/:id',
    viewNextWebBranding: '/settings/nextWeb/branding/view/:id'
  },
  distributionTracing: {
    livemap: '/distribution-tracing/livemap',
    livemapDetail: '/distribution-tracing/livemap/detail',
    service: '/distribution-tracing/service',
    serviceDetail: '/distribution-tracing/service/detail/:id',
    traces: '/distribution-tracing/traces',
    tracesDetail: '/distribution-tracing/traces/detail/:id',
    tracesDetailTime: '/distribution-tracing/traces/detail/time/:id'
  },
  monitoringAlerting: {
    monitoringGraph: '/monitoring-alerting/monitoring-graph',
    addNewVariable: '/monitoring-alerting/monitoring-graph/add-new-variable',
    editVariable: '/monitoring-alerting/monitoring-graph/detail/:id/edit-variable/:id',
    createGraph: '/monitoring-alerting/monitoring-graph/create-graph',
    viewDetails: '/monitoring-alerting/monitoring-graph/detail/:id',
    alertingChannels: '/monitoring-alerting/alerting/channels',
    alertingRules: '/monitoring-alerting/alerting/rules',
    alertingRulesAdd: '/monitoring-alerting/alerting/rules/add',
    alertingRulesChooseType: '/monitoring-alerting/alerting/rules/type',
    alertingTriggers: '/monitoring-alerting/alerting/triggers',
    alertingChannelAdd: '/monitoring-alerting/alerting/channel/add'
  },
  userAndRoles: {
    clusterRoles: '/user-and-roles/cluster-roles',
    clusterRolesDetail: '/user-and-roles/cluster-roles/detail/:id',
    editClusterRolesDetail: '/user-and-roles/cluster-roles/detail/:id/edit/:id',
    clusterRolesBindings: '/user-and-roles/cluster-roles-bindings',
    clusterRolesBindingsDetail:
      'user-and-roles/cluster-roles-bindings/detail/:id',
    editClusterRolesBindingsDetail:
      'user-and-roles/cluster-roles-bindings/detail/:id/edit/:id',
    clusterRolesBindingsResourceInformation:
      'user-and-roles/cluster-roles-bindings/detail/:id/resource-information',
    roles: '/user-and-roles/roles',
    rolesDetail: '/user-and-roles/roles/detail/:id',
    rolesDetailEdit: '/user-and-roles/roles/detail/:id/edit',
    rolesBindings: '/user-and-roles/roles-bindings',
    rolesBindingsDetail: '/user-and-roles/roles-bindings/detail/:id',
    rolesBindingsDetailEdit: '/user-and-roles/roles-bindings/detail/:id/edit',
    rolesBindingsDetailResourcesInformation:
      '/user-and-roles/roles-bindings/detail/:id/resources-information',
    rolesBindingsDetailResourcesInformationEdit:
      '/user-and-roles/roles-bindings/detail/:id/resources-information/edit',
    servicesAccounts: '/user-and-roles/service-accounts',
    editServiceAccounts: '/user-and-roles/service-accounts/edit/:id',
    addServiceAccounts: '/user-and-roles/service-accounts/add',
    servicesAccountsDetail: '/user-and-roles/service-accounts/detail/:id',
    editservicesAccountsDetail:
      'user-and-roles/service-accounts/detail/:id/edit/:id',
    serviceAccountsDetailSecretDetail:
      '/user-and-roles/service-accounts/detail/:id/secret-detail/:id',
    editservicesAccountsSecretDetail:
      '/user-and-roles/service-accounts/detail/:id/secret-detail/:id/edit/:id',
    users: '/user-and-roles/users'
  },
  appManagement: {
    dashboard: '/app-management/dashboard',
    applications: '/app-management/applications',
    applicationsSyncAll: '/app-management/applications/sync-all',
    applicationsSyncApp: '/app-management/applications/sync-app/:id',
    applicationsSyncNodes: '/app-management/applications/:id/sync-nodes',
    applicationsAddApplication: '/app-management/applications/add-application',
    applicationGuestBookSVC: '/app-management/applications/:id/guestbook/SVC',     // DUMMY, PLEASE CHANGE DUMMY, PLEASE CHANGE DUMMY, PLEASE CHANGE DUMMY, PLEASE CHANGE
    applicationGuestBookDeploy: '/app-management/applications/:id/guestbook/deploy',     // DUMMY, PLEASE CHANGE DUMMY, PLEASE CHANGE DUMMY, PLEASE CHANGE DUMMY, PLEASE CHANGE
    applicationsMap: '/app-management/applications/:id',
    applicationsDetail: '/app-management/applications/:id/detail',
    userManagement: '/app-management/user-management',
    userManagementDetail: '/app-management/user-management/detail/:id',
    settingRepositories: '/app-management/setting/repositories',
    settingRepositoriesAddSSH: '/app-management/setting/repositories/add-ssh',
    settingRepositoriesAddHTTPS: '/app-management/setting/repositories/add-https',
    settingRepositoriesAddGithub: '/app-management/setting/repositories/add-github',
    settingCertificates: '/app-management/setting/certificates',
    settingCertificatesAddTLS: '/app-management/setting/certificates/add-tls',
    settingCertificatesAddSSH: '/app-management/setting/certificates/add-ssh',
    settingClusters: '/app-management/setting/clusters',
    detailClusters: '/app-management/setting/clusters/detail-clusters/:id',
    settingProjects: '/app-management/setting/projects',
    settingAddProjects: '/app-management/setting/add-projects',
    settingProjectsDetail: '/app-management/setting/projects/detail/:id',
    helpOverview: '/app-management/help/overview',
    helpUnderstandTheBasic: '/app-management/help/understand-the-basic',
    helpCoreConcept: '/app-management/help/core-concept',
    helpGettingStarted: '/app-management/help/getting-started',
    helpOperatorManual: '/app-management/help/operator-manual',
    helpUserGuide: '/app-management/help/user-guide',
    helpDeveloperGuide: '/app-management/help/developer-guide',
    helpFAQ: '/app-management/help/faq',
    helpSecurityConsideration: '/app-management/help/security-consideration',
    helpSupport: '/app-management/help/support',
    helpRoadmap: '/app-management/help/roadmap',
    helpReleases: '/app-management/help/releases',
    helpBlog: '/app-management/help/blog'
  }
};

const shouldMenuShow = (menu: string) => {
  const location = window.location.pathname;

  return !location.includes(menu);
};

export { allRoutes, navIds, shouldMenuShow };
